/*
 * Aineopintojen harjoitustyö: Tietorakenteet ja algoritmit
 * Helsingin yliopisto Tietojenkäsittelytieteen laitos
 * Ooppa 2015 - GNU General Public License, version 3.
 */
package application;

import domain.RecommendedItem;
import domain.User;
import generators.TestDataGenerator;
import java.util.ArrayList;

/**
 * Example of the algorithm in action
 *
 * @author Ooppa
 */
public class Example {

    private TestDataGenerator data;

    /**
     * Creates a new Example to be used to try out the algorithm
     */
    public Example() {
        // Start by generating the test data.
        data = new TestDataGenerator(true, 1000);

        Engine engine = new Engine();

        // We get our example user
        User exampleUser = data.getUsers().get(0);

        // Using Slope One
        ArrayList<RecommendedItem> rateItemsBasedOnUserReviews = engine.rateItemsBasedOnUserReviews(exampleUser, data.getUsers(), data.getItems());

        // Print TOP-10 recommendations for the example user
        for(int i = 0; i<10; i++) {
            RecommendedItem item = rateItemsBasedOnUserReviews.get(i);

            System.out.println(i+": "+item.toString());

            ArrayList<RecommendedItem> rateItemsBasedOnQualities = engine.rateItemsBasedOnQualities(item.getItem(), data.getItems());

            // And similar items to the top-10 list
            for(int j = 0; j<5; j++) {
                System.out.println("\t"+i+": "+rateItemsBasedOnQualities.get(i).toString());
            }
        }

    }

    /**
     * Returns the data generated for the Example
     *
     * @return the data generated by TestDataGenerator
     */
    public TestDataGenerator getData() {
        return data;
    }

}
