/*
 * Aineopintojen harjoitustyö: Tietorakenteet ja algoritmit
 * Helsingin yliopisto Tietojenkäsittelytieteen laitos
 * Ooppa 2015 - GNU General Public License, version 3.
 */
package application;

import domain.RecommendedItem;
import domain.User;
import generators.TestDataGenerator;
import java.util.ArrayList;
import java.util.HashMap;

/**
 * Example of the algorithm in action
 *
 * @author Ooppa
 */
public class Example {

    private final TestDataGenerator data;

    /**
     * Creates a new Example to be used to try out the algorithm
     */
    public Example() {
        System.out.println("----------------- STARTING ------------------");

        // Start by generating the test data.
        data = new TestDataGenerator(true, 400);

        Algorithm algorithm = new Algorithm();

        HashMap<Long, User> users = data.getUsers();
        User user = users.get(2000L);

        users.remove(user.getId());

        System.out.println("----------------- ALGORITHM ------------------");

        ArrayList<RecommendedItem> recommendedItems = algorithm.recommendItems(user, users, data.getItems());

        System.out.println("---------------- TOP 10 ITEMS ----------------");

        // If over 10 RecommendedItems in list
        if(recommendedItems.size()>10) {
            for(int i = 0; i<10; i++) {
                System.out.println(recommendedItems.get(i));
            }
        }
    }

    /**
     * Returns the data generated for the Example
     *
     * @return the data generated by TestDataGenerator
     */
    public TestDataGenerator getData() {
        return data;
    }

}
